import type { PropertyLead } from "./types";

export const sampleLeads: PropertyLead[] = [
  {
    id: "lead-001",
    owner: "Maya Thompson",
    address: "114 Palmerston Ave",
    city: "Toronto",
    province: "ON",
    postalCode: "M6J 2J1",
    email: "maya@thompsonstudio.ca",
    phone: "+1 (416) 555-0182",
    propertyType: "Detached",
    confidence: 96,
    status: "verified",
    databaseStatus: "verified",
    updatedAt: "18 sec ago",
    sources: [
      { label: "Business registry", url: "https://ised-isde.canada.ca/", detail: "Owner and company address alignment", capturedAt: "Today, 12:42 PM" },
      { label: "Company website", url: "https://example.com/", detail: "Public contact page email", capturedAt: "Today, 12:42 PM" },
      { label: "Municipal record", url: "https://www.toronto.ca/", detail: "Property address confirmation", capturedAt: "Today, 12:41 PM" },
    ],
  },
  {
    id: "lead-002",
    owner: "Ravi & Neha Patel",
    address: "28 Withrow Ave",
    city: "Toronto",
    province: "ON",
    postalCode: "M4K 1C9",
    email: "rpatel@northpeakgroup.com",
    phone: "+1 (647) 555-0137",
    propertyType: "Semi-detached",
    confidence: 91,
    status: "verified",
    databaseStatus: "verified",
    updatedAt: "1 min ago",
    sources: [
      { label: "Corporate directory", url: "https://ised-isde.canada.ca/", detail: "Name, city and employer match", capturedAt: "Today, 12:40 PM" },
      { label: "Professional profile", url: "https://www.linkedin.com/", detail: "Public company affiliation", capturedAt: "Today, 12:40 PM" },
    ],
  },
  {
    id: "lead-003",
    owner: "Elena Moretti",
    address: "602 St Clair Ave W",
    city: "Toronto",
    province: "ON",
    postalCode: "M6C 1A9",
    email: null,
    phone: "+1 (416) 555-0144",
    propertyType: "Mixed use",
    confidence: 74,
    status: "reviewing",
    databaseStatus: "researching",
    updatedAt: "2 min ago",
    sources: [
      { label: "Public directory", url: "https://www.canada411.ca/", detail: "Phone and neighbourhood match", capturedAt: "Today, 12:38 PM" },
    ],
  },
  {
    id: "lead-004",
    owner: "Claremont Holdings Inc.",
    address: "77 Bloor St W",
    city: "Toronto",
    province: "ON",
    postalCode: "M5S 1M2",
    email: "leasing@claremont-holdings.ca",
    phone: "+1 (416) 555-0169",
    propertyType: "Commercial",
    confidence: 98,
    status: "verified",
    databaseStatus: "verified",
    updatedAt: "3 min ago",
    sources: [
      { label: "Company website", url: "https://example.com/", detail: "Domain and legal entity match", capturedAt: "Today, 12:37 PM" },
      { label: "Ontario registry", url: "https://www.ontario.ca/page/ontario-business-registry", detail: "Active corporation and registered address", capturedAt: "Today, 12:37 PM" },
    ],
  },
  {
    id: "lead-005",
    owner: "Jordan Lee",
    address: "319 Sorauren Ave",
    city: "Toronto",
    province: "ON",
    postalCode: "M6R 2G5",
    email: null,
    phone: null,
    propertyType: "Townhouse",
    confidence: 41,
    status: "attention",
    databaseStatus: "needs_review",
    updatedAt: "4 min ago",
    sources: [
      { label: "Municipal record", url: "https://www.toronto.ca/", detail: "Property confirmed; identity is ambiguous", capturedAt: "Today, 12:35 PM" },
    ],
  },
  {
    id: "lead-006",
    owner: "Sofia Bennett",
    address: "841 Queen St E",
    city: "Toronto",
    province: "ON",
    postalCode: "M4M 1H9",
    email: null,
    phone: null,
    propertyType: "Retail",
    confidence: 0,
    status: "queued",
    databaseStatus: "queued",
    updatedAt: "Queued",
    sources: [],
  },
];
